# Generated by Django 5.2.3 on 2025-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
    ]
